services:
  redis:
    image: redis
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
