# Generated by Django 5.2.9 on 2025-12-10 20:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("rss", "0001_initial"),
        ("rss", "0002_feed_torrent_seen"),
        ("rss", "0003_feed_download_dir_transmissionclient"),
        ("rss", "0004_remove_torrent_contents_remove_torrent_info_hash_and_more"),
        ("rss", "0005_alter_feed_expire_alter_transmissionclient_feeds"),
        ("rss", "0006_remove_transmissionclient_feeds_and_more"),
        ("rss", "0007_torrent_published"),
        ("rss", "0008_feed_ignore_older_than_transmissionclient_name"),
        ("rss", "0009_feed_ignore_newer_than_alter_feed_expire_and_more"),
        ("rss", "0010_rename_expire_feed_expires_at"),
        ("rss", "0011_transmissionclient_protocol_and_more"),
        ("rss", "0012_feed_start_paused_alter_transmissionclient_password_and_more"),
        ("rss", "0013_feed_regex_filter"),
        ("rss", "0014_feed_chronological"),
        ("rss", "0015_feed_last_activity_feed_name"),
        ("rss", "0016_feed_enabled"),
        ("rss", "0017_torrent_created_at_torrent_updated_at"),
        ("rss", "0018_alter_torrent_options"),
        ("rss", "0019_alter_feed_options_feed_created_at_feed_updated_at"),
        ("rss", "0020_feed_last_added"),
        ("rss", "0021_alter_feed_regex_filter"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransmissionClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=2048)),
                ("port", models.CharField(default="9091", max_length=10)),
                ("username", models.CharField(blank=True, max_length=2048)),
                ("password", models.CharField(blank=True, max_length=2048)),
                ("name", models.CharField(default="transmission", max_length=2048)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("http", "http"), ("https", "https")],
                        default="http",
                        max_length=10,
                    ),
                ),
                (
                    "rpc_path",
                    models.CharField(default="/transmission/", max_length=2048),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Torrent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2048)),
                ("link", models.URLField()),
                ("published", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "-published"),
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Skip feed fetch after this date",
                        null=True,
                    ),
                ),
                ("download_dir", models.CharField(blank=True, max_length=2048)),
                (
                    "transmission_clients",
                    models.ManyToManyField(
                        blank=True, related_name="feeds", to="rss.transmissionclient"
                    ),
                ),
                (
                    "ignore_older_than",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ignore older torrents than this date",
                        null=True,
                    ),
                ),
                (
                    "ignore_newer_than",
                    models.DateTimeField(
                        blank=True,
                        help_text="Ignore newer torrents than this date",
                        null=True,
                    ),
                ),
                (
                    "start_paused",
                    models.BooleanField(
                        default=False, help_text="Start torrents paused"
                    ),
                ),
                ("regex_filter", models.CharField(blank=True, max_length=2048)),
                (
                    "chronological",
                    models.BooleanField(
                        default=True, help_text="Add torrents in chronological order"
                    ),
                ),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=2048)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_added",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
