# Generated by Django 4.1.2 on 2022-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0005_alter_feed_expire_alter_transmissionclient_feeds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transmissionclient",
            name="feeds",
        ),
        migrations.AddField(
            model_name="feed",
            name="transmission_clients",
            field=models.ManyToManyField(
                blank=True, related_name="feeds", to="rss.transmissionclient"
            ),
        ),
    ]
