# Generated by Django 4.1.2 on 2022-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0006_remove_transmissionclient_feeds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
