# Generated by Django 4.1.2 on 2022-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0008_feed_ignore_older_than_transmissionclient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="ignore_newer_than",
            field=models.DateTimeField(
                blank=True, help_text="Ignore newer torrents than this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="expire",
            field=models.DateTimeField(
                blank=True, help_text="Skip feed fetch after this date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="ignore_older_than",
            field=models.DateTimeField(
                blank=True, help_text="Ignore older torrents than this date", null=True
            ),
        ),
    ]
