# Generated by Django 4.1.2 on 2022-10-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0010_rename_expire_feed_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmissionclient",
            name="protocol",
            field=models.CharField(
                choices=[("http", "http"), ("https", "https")],
                default="http",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transmissionclient",
            name="rpc_path",
            field=models.CharField(default="/transmission/", max_length=2048),
        ),
        migrations.AlterField(
            model_name="transmissionclient",
            name="name",
            field=models.CharField(default="transmission", max_length=2048),
        ),
        migrations.AlterField(
            model_name="transmissionclient",
            name="port",
            field=models.CharField(default="9091", max_length=10),
        ),
    ]
