# Generated by Django 4.1.2 on 2022-10-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0011_transmissionclient_protocol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="start_paused",
            field=models.BooleanField(default=False, help_text="Start torrents paused"),
        ),
        migrations.AlterField(
            model_name="transmissionclient",
            name="password",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="transmissionclient",
            name="username",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
