# Generated by Django 4.1.6 on 2023-02-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0014_feed_chronological"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="name",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
