# Generated by Django 4.1.6 on 2024-04-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0017_torrent_created_at_torrent_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="torrent",
            options={"ordering": ("-created_at", "-published")},
        ),
    ]
