# Generated by Django 4.1.6 on 2024-04-03 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0018_alter_torrent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feed",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="feed",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feed",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
