# Generated by Django 4.1.6 on 2024-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0019_alter_feed_options_feed_created_at_feed_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="last_added",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
