# Generated by Django 5.2.9 on 2025-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0020_feed_last_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="regex_filter",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
