# Generated by Django 5.2.9 on 2025-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_squashed_0021_alter_feed_regex_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="torrent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
