# Generated by Django 5.2.9 on 2025-12-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("rss", "0022_alter_feed_created_at_alter_torrent_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
