# Generated by Django 5.2.9 on 2026-09-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0023_feed_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmissionclient",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("transmission", "transmission"),
                    ("qbittorrent", "qbittorrent"),
                ],
                default="transmission",
                max_length=50,
            ),
        ),
    ]
