# Generated by Django 5.2.9 on 2026-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0024_transmissionclient_client_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransmissionClient",
            new_name="TorrentClient",
        ),
    ]
