# Generated by Django 5.2.9 on 2026-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0025_rename_transmissionclient_torrentclient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrentclient",
            name="name",
            field=models.CharField(default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="torrentclient",
            name="port",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="torrentclient",
            name="rpc_path",
            field=models.CharField(default="/", max_length=2048),
        ),
    ]
