# Generated by Django 5.2.9 on 2026-09-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0026_alter_torrentclient_name_alter_torrentclient_port_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="torrentclient",
            old_name="rpc_path",
            new_name="base_path",
        ),
    ]
