# Generated by Django 5.2.9 on 2026-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0027_rename_rpc_path_torrentclient_base_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torrentclient",
            name="base_path",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="torrentclient",
            name="port",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
