# Generated by Django 5.2.9 on 2026-09-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0028_alter_torrentclient_base_path_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="transmission_clients",
            new_name="torrent_clients",
        ),
    ]
