# Generated by Django 5.2.9 on 2026-09-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0029_rename_transmission_clients_feed_torrent_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrent",
            name="feed",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="torrents",
                to="rss.feed",
            ),
        ),
        migrations.AddField(
            model_name="torrent",
            name="torrent_client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="torrents",
                to="rss.torrentclient",
            ),
        ),
    ]
