# Generated by Django 5.2.9 on 2026-09-27 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0030_torrent_feed_torrent_torrent_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="torrentclient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="torrentclient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
