# Generated by Django 5.2.9 on 2026-09-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0031_torrentclient_created_at_torrentclient_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="enabled",
        ),
    ]
