# Generated by Django 5.2.9 on 2026-09-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0032_remove_feed_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="last_activity",
            new_name="last_check",
        ),
    ]
