# Generated by Django 5.2.9 on 2026-10-01 13:34

import django.db.models.deletion
from django.db import migrations, models

from rss.models import Feed, torrent_client


def forwards_func(apps, schema_editor):
    Feed = apps.get_model("rss", "Feed")
    db_alias = schema_editor.connection.alias
    feeds = Feed.objects.using(db_alias).all()
    for feed in feeds:
        feed.torrent_client = feed.torrent_clients.first()
        feed.save()


def reverse_func(apps, schema_editor):
    Feed = apps.get_model("rss", "Feed")
    db_alias = schema_editor.connection.alias
    feeds = Feed.objects.using(db_alias).all()
    for feed in feeds:
        feed.torrent_clients.add(feed.torrent_client)


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0033_rename_last_activity_feed_last_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="torrent_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeds",
                to="rss.torrentclient",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name="feed",
            name="torrent_clients",
        ),
    ]
