name: Build and push docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    concurrency:
      group: ${{ github.ref }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v7

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get tag info
        id: tags
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s)
          tag_latest="ghcr.io/${{ github.repository_owner }}/mission-commander:latest"
          tag_sha_ts="ghcr.io/${{ github.repository_owner }}/mission-commander:${{ github.ref }}-$sha-$ts"
          tag_ref="ghcr.io/${{ github.repository_owner }}/mission-commander:${{ github.ref }}"
          echo "tag_latest=$tag_latest" >> $GITHUB_OUTPUT
          echo "tag_sha_ts=$tag_sha_ts" >> $GITHUB_OUTPUT
          echo "tag_ref=$tag_ref" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          docker build . --file Dockerfile \
            --tag ${{ steps.tags.outputs.tag_latest }} \
            --tag ${{ steps.tags.outputs.tag_sha_ts }} \
            --tag ${{ steps.tags.outputs.tag_ref }} \
            --push
